### PR TITLE
Disable logging in Release

### PR DESCRIPTION
**Pull request by aw-c**
We have some troubles with SS14 servers ( [Our discord](https://discord.gg/ss220) ) with DDoS attacks from someone so it will be cool if you accept these changes please

### CODE REVIEW

**Comment by metalgearsloth** [comment]
Error logs shouldn't be wrapped in debug tags as then logging becomes entirely useless. Resolve the DDOS attacks as a host.

**Comment by aw-c** [comment]
> Error logs shouldn't be wrapped in debug tags as then logging becomes entirely useless. Resolve the DDOS attacks as a host.

We can't fix it without editing engine

**Comment by ElectroJr** [comment]
> We can't fix it without editing engine

Engine/lidgren contributions are welcome, and we would appreciate PRs that help improve networking resilience, error handling, or logging performance, but just blanket disabling of error logs in release mode doesn't address whatever the issue was.

If you really want to disable lidgren logging, then at the very least it needs to be configurable, though if the DDoS was just causing a specific error to be logged way too many times, maybe add some rate limit for that error?

**Comment by PJB3005** [comment]
What makes you think that disabling logging will solve the DDoS attack? Do you have profile results indicating that this is where the major source of load comes from?

**Comment by aw-c** [comment]
> What makes you think that disabling logging will solve the DDoS attack? Do you have profile results indicating that this is where the major source of load comes from?

Because we have 11Gb logs about just that one errno, attack is not pointing on networks, it's on CPU and I/O shit.

**Pull request closed without merging**
